import 'dart:math';

import '../class/meals.dart';
import './ing.dart';

List<String> mainDishCategories = [
  "All",
  "Breakfast",
  "Pasta",
  "Persian",
  "Salad",
];

List<Meals> myMeals = [
  Meals(
    name: "Pancakes",
    difficulty: "Easy",
    url: "assets/images/meals/breakfast/Pancakes.jpg",
    ingredients: {
      egg: "3",
      backingPowder: "1.5 Teaspoon",
      sugar: "1 Tablespoon",
      flour: "200g",
      butter: "25g",
      milk: "200ml",
    },
    category: "Breakfast",
    description:
        "Step 1 :\nMix 200g self-raising flour, 1 ½ tsp baking powder, 1 tbsp golden caster sugar and a pinch of salt together in a large bowl.\n\nStep 2 :\nCreate a well in the centre with the back of your spoon then add 3 large eggs, 25g melted butter and 200ml milk.\n\nStep 3 :\nWhisk together either with a balloon whisk or electric hand beaters until smooth then pour into a jug.\n\n Step 4 :\nHeat a small knob of butter and 1 tsp of oil in a large, non-stick frying pan over a medium heat. When the butter looks frothy, pour in rounds of the batter, approximately 8cm wide. Make sure you don’t put the pancakes too close together as they will spread during cooking. Cook the pancakes on one side for about 1-2 mins or until lots of tiny bubbles start to appear and pop on the surface. Flip the pancakes over and cook for a further minute on the other side. Repeat until all the batter is used up.\n\nStep 5 :\nServe your pancakes stacked up on a plate with a drizzle of maple syrup and any of your favourite toppings.",
    time: "50m",
  ),
  Meals(
    name: "Overnight Oats",
    difficulty: "Easy",
    url: "assets/images/meals/breakfast/OvernightOats.jpg",
    ingredients: {
      cinnamon: "0.25 Teaspoon",
      bean: "50g Oats",
      yogurt: "2 Tablespoon",
      strawberry: "15g",
      blackberry: "15g",
      blueberry: "15g",
      raspberry: "15g",
      honey: "a Drizzle",
      butter: "0.5 Tablespoon Nut Butter",
    },
    category: "Breakfast",
    description:
        "Step 1 :\nThe night before serving, stir the cinnamon and 100ml water (or milk) into your oats with a pinch of salt.\n\nStep 2 :\nThe next day, loosen with a little more water (or milk) if needed. Top with the yogurt, berries, a drizzle of honey and the nut butter.",
    time: "10m",
  ),
  Meals(
    name: "Beans & Cheese",
    difficulty: "Easy",
    url: "assets/images/meals/breakfast/TurboBeansAndCheese.jpg",
    ingredients: {
      oil: "2 Tablespoon Vegetable Oil",
      onion: "1",
      garlic: "4 Cloves",
      powder: "1 Teaspoon Smoked Paprika",
      powderD1: "1 Teaspoon Cumin",
      pepper: "Chipotle Chilli Paste to taste",
      tomato: "200g",
      bean: "800g Gean Bean",
      cheese: "150g Cheddar",
      bread: "4-8 Slices",
    },
    category: "Breakfast",
    description:
        "Step 1 :\nHeat the oil in a heavy-based frying pan over a medium heat and fry the onion for 8-10 mins until softened and slightly caramelised. Add the garlic and spices, the chipotle chilli paste or chilli flakes, if using, and some seasoning. Fry for a few minutes more until the mixture is fragrant.\n\nStep 2 :\nAdd the tomatoes, then swirl out the pan using 100ml water and add this too. Simmer for 10-15 mins until the mixture has thickened. Blitz the sauce using a hand blender, then taste for seasoning. Tip in the beans and mix well to coat. Warm through over a medium heat for 5 mins until the beans are piping hot.\n\nStep 3 :\nHeat the grill to high and toast the bread slices for 3-5 mins. Top with the beans and grated cheese, and pop under the grill until the cheese is melted and bubbling. Sprinkle with a little paprika and serve immediately.",
    time: "40m",
  ),
  Meals(
    name: "Eggy Cheese Crumpets",
    difficulty: "Easy",
    url: "assets/images/meals/breakfast/EggyCheeseCrumpets.jpg",
    ingredients: {
      egg: "3",
      milk: "50ml",
      bread: "6 Crumpets",
      tomato: "250g Cherry Tomatoes",
      oil: "Drizzle of Vegetable oil",
      cheese: "40g Cheddar",
      raspberry: "50g",
      strawberry: "50g",
    },
    category: "Breakfast",
    description:
        "Step 1 :\nHeat the grill. Beat the eggs and milk together in a wide dish. Submerge the crumpets in the egg mixture, turning them once, then set aside for a few minutes.\n\nStep 2 :\nArrange the tomatoes cut-side up on a baking tray and grill for a few minutes, then cover the tray with foil to keep the tomatoes warm.\n\nStep 3 :\nHeat the oil in a frying pan and cook the crumpets for a few minutes on each side until the egg has set – you may have to do this in batches. Transfer them to a baking tray as you go. Once all the crumpets are cooked, top with the cheese and grill for 1-2 mins until the cheese is bubbling and golden. Serve with the tomatoes and Berries.",
    time: "15m",
  ),
  Meals(
    name: "Soft-Boiled Eggs",
    difficulty: "Easy",
    url: "assets/images/meals/breakfast/SoftBoiledEggs.jpg",
    ingredients: {
      egg: "2",
    },
    category: "Breakfast",
    description:
        "Step 1 :\nFill a medium sized saucepan with water and bring to a rolling boil.\n\nStep 2 :\nMake sure your eggs aren't fridge cold. By having the eggs at room temperature, it will be less of a shock for the egg reaching the hot water and therefore less likely to crack. You can also use an egg pricker to make a very small hole in each egg before boiling, which will also reduce the chances of it cracking in the heat. Slowly lower the eggs into the water using a spoon.\n\nStep 3 :\nSet your timer for 4-5 mins for runny/dippy eggs to serve with soldiers, or 6-7 mins for soft-boiled eggs for a salad. If serving in a salad, plunge the eggs into a bowl of cold water as soon as the timer goes off – this will stop them cooking and cool the shells quickly for peeling.",
    time: "10m",
  ),
  Meals(
    name: "Egg Wraps",
    difficulty: "Easy",
    url: "assets/images/meals/breakfast/EggWraps.jpg",
    ingredients: {
      mushroom: "500g",
      oil: "4 Teaspoon Rapeseed oil",
      tomato: "320g Cherry tomatoes",
      parsley: "2 Generous handfuls ",
      bean: "8 Tablespoon Oats(40g)",
      egg: "10",
      mustard: "4 TSP English mustardpowder",
    },
    category: "Breakfast",
    description:
        "Step 1 :\nThickly slice half the pack of mushrooms. Heat 2 tsp rapeseed oil in a non-stick pan. Add the mushrooms, stir briefly then fry with the lid on the pan for 6-8 mins. Stir in half the tomatoes then cook 1-2 mins more with the lid off until softened.\n\nStep 2 :\nBeat together the eggs really well with the parsley and oats. Heat a drop of oil in a large non-stick frying pan. Pour in a ¼ of the egg mix and fry for 1 min until almost set, flip over as if making a pancake. Tip from the pan, spread with a quarter of the mustard, spoon a ¼ the filling down the centre and roll up. Now make a second wrap using another ¼ of the egg mix and filling. If you're following our Healthy Diet Plan, save the rest for the following day.",
    time: "15m",
  ),
  Meals(
    name: "Breakfast Burrito",
    difficulty: "Easy",
    url: "assets/images/meals/breakfast/BreakfastBurrito.jpg",
    ingredients: {
      sauce: "1 Teaspoon Chipotle paste",
      egg: "1",
      oil: "1 Teaspoon Rapeseed oil",
      herb: "50g Kale",
      tomato: "7 Cherry tomatoes",
      raspberry: "20g",
      strawberry: "20g",
      bread: "1 Wholemeal tortilla",
    },
    category: "Breakfast",
    description:
        "Step 1 :\nWhisk the chipotle paste with the egg and some seasoning in a jug. Heat the oil in a large frying pan, add the kale and tomatoes.\n\nStep 2 :\nCook until the kale is wilted and the tomatoes have softened, then push everything to the side of the pan. Pour the beaten egg into the cleared half of the pan and scramble. Layer everything into the centre of your wrap, topping with the berries, then wrap up and eat immediately.",
    time: "15m",
  ),
  Meals(
    name: "High Protein Breakfast",
    difficulty: "Easy",
    url: "assets/images/meals/breakfast/HighProteinBreakfast.jpg",
    ingredients: {
      oliveOil: "15ml",
      tomato: "130g",
      bacon: "4 Rashers turkey",
      meat: "180g Sirloin steak",
      mushroom: "150g",
      herb: "160g Spinach",
      egg: "1",
    },
    category: "Breakfast",
    description:
        "Step 1 :\nHeat grill to high. Drizzle a little of the oil on your tomatoes and season well. Lay the tomatoes on a baking tray lined with foil and place under the grill. Cook for 4-5 mins, then add the bacon to the tray. Turn the bacon as necessary until it is cooked through. Turn off the grill and shut the door to keep everything warm.\n\nStep 2 :\nMeanwhile, heat the remaining oil in a large, non-stick frying pan over a high heat. Season your steak well and, when the pan is very hot, fry for 3-4 mins each side for medium-rare, then leave it to rest until you are ready to eat.\n\nStep 3 :\nWhile the steak is resting, throw the mushrooms into the still-hot pan, fry for 2-3 mins until browned, then move to one side of the pan. Add the spinach to the other side of the pan and cook until wilted. Put a saucepan of water on to boil.\n\nStep 4 :\nCrack the egg into the boiling water, then reduce the heat until the water is gently simmering. Poach the egg for 3-4 mins or until the white has set but the yolk is still runny. Carefully lift it out with a slotted spoon and drain on kitchen paper. Serve everything together and top with the poached egg.",
    time: "25m",
  ),
  Meals(
    name: "Tofu Scramble",
    difficulty: "Easy",
    url: "assets/images/meals/breakfast/TofuScramble.jpg",
    ingredients: {
      oliveOil: "1 Tablespoon",
      onion: "1",
      garlic: "1 Clove",
      powder: "0.5 Teaspoon Turmeric",
      powderD1: "1 Teaspoon Cumin",
      powderD1: "0.5 Teaspoon smoked Paprika",
      milk: "280g Tofu",
      tomato: "100g Cherry tomato",
      parsley: "Bunch of it",
      bread: "For Serve",
    },
    category: "Breakfast",
    description:
        "Step 1 :\nHeat the oil in a frying pan over a medium heat and gently fry the onion for 8 -10 mins or until golden brown and sticky. Stir in the garlic, turmeric, cumin and paprika and cook for 1 min.\n\nStep 2 :\nRoughly mash the tofu in a bowl using a fork, keeping some pieces chunky. Add to the pan and fry for 3 mins. Raise the heat, then tip in the tomatoes, cooking for 5 mins more or until they begin to soften. Fold the parsley through the mixture. Serve on its own or with toasted rye bread (not gluten-free), if you like.",
    time: "30m",
  ),
  Meals(
    name: "Salsa Verde Baked Eggs",
    difficulty: "Easy",
    url: "assets/images/meals/breakfast/SalsaVerdeBakedEggs.jpg",
    ingredients: {
      oliveOil: "5 Tablespoon",
      powder: "1 Teaspoon smoked Paprika",
      powderD1: "1 Teaspoon Cumin",
      tomato: "600g Cherry Tomatoes",
      garlic: "2 Cloves",
      parsley: "Bunch of it",
      basil: "Bunch of it",
      herb: "Bunch of mint",
      bean: "2 Tablespoon Capers",
      mustard: "1 Teaspoon Dijon mustard",
      vinegar: "2 Tablespoon white wine Vinegar",
      herbD1: "200g baby Spinach",
      egg: "4",
      pepper: "0.5 Teaspoon Chilli flakes",
      bread: "For serve",
    },
    category: "Breakfast",
    description:
        "Step 1 :\nDrizzle 1 tbsp of the olive oil in a frying pan or skillet, and fry the paprika and cumin for 30 seconds over a medium heat. Add the canned tomatoes and fresh tomatoes, bring to the boil, then simmer with a lid on over a medium heat for 5-6 mins until the tomatoes have softened.\n\nStep 2 :\nMeanwhile, put the garlic, most of the parsley, the basil, mint, capers, mustard, white wine vinegar, 4 tbsp oil and 3 tbsp cold water in a mini food processor and blitz to a smooth paste. Season.\n\nStep 3 :\nStir the spinach into the pan with the tomatoes until wilted (put the lid back on for a few minutes, then stir again to help it wilt). Make four dips in the mixture and gently crack an egg into each one. Cover with a lid and cook over a medium heat for 6-8 mins, or until the eggs are just set. Uncover the pan, then drizzle over the herby sauce. Scatter over the reserved parsley and chilli flakes, if using. Serve with flatbreads, if you like.",
    time: "20m",
  ),
  Meals(
    name: "Bacon Pancakes",
    difficulty: "Easy",
    url: "assets/images/meals/breakfast/BP.jpg",
    ingredients: {
      bacon: "8 Pieces",
      egg: "3",
      oil: "3 Tablespoon",
      salt: "0.25 Teaspoon",
      backingPowder: "2 Teaspoon",
      flour: "2 Cups",
      sugar: "1 Tablespoon",
      milk: "2 Cups",
    },
    category: "Breakfast",
    description:
        "Step 1 :\nWhisk together the ingredients for the pancake batter. Allow to sit.\n\nStep 2 :\nOn a hot griddle or large pan, cook the bacon. Remove to a paper towel and allow the grease to come off.\n\nStep 3 :\nWipe the griddle or pan down with a paper towel. Depending on how much space you have, add a few pieces of bacon at a time and spoon a small portion of the pancake mix over each slice of bacon. Make sure the bacon is fully covered, but don't make them too thick.\n\nStep 4 :\nCooking on medium heat, flip pancakes after 2-3 minutes (you'll know they need flipped when the batter on the top becomes filled with little bubbles).\n\nStep 5 : Remove to a plate and keep warm while cooking remaining pieces of bacon.",
    time: "30m",
  ),
  Meals(
    name: "Poached Eggs",
    difficulty: "Easy",
    url: "assets/images/meals/breakfast/PoachedEggs.jpg",
    ingredients: {
      egg: "As many as you want",
    },
    category: "Breakfast",
    description:
        "Step 1 :\nFill a large saucepan with water and add the vinegar. As soon as the water starts to boil, turn the heat down to a simmer.\n\nStep 2 :\nCrack the egg into a small bowl. For a perfect egg with no wispy white bits, crack into a fine strainer and allow the runnier egg white to drain off. Then carefully slide the egg into the water and cook for 3-4 mins, until the white is cooked through. Remove gently using a slotted spoon and blot any water from the base on a tea towel or kitchen paper. You can add more than one egg to the pan but make sure each one has enough room.",
    time: "10m",
  ),
  Meals(
    name: "Air Fryer Bacon",
    difficulty: "Easy",
    url: "assets/images/meals/breakfast/AirFryerBacon.jpg",
    ingredients: {
      bacon: "6 rashes streaky",
    },
    category: "Breakfast",
    description:
        "Step 1 :\nLay the bacon in a single layer in the base of an air fryer – be sure the layers aren't overlapping. The size of the air fryer basket will determine how many rashers you can cook at one time.\n\nStep 2 :\nSet the air fryer to 200C and cook streaky bacon rashers for 6-10 mins – just-cooked bacon will take 6 mins, but crispier bacon will take 9-10 mins. Cook back bacon rashers for 4-8 mins, depending on your preference. If you are cooking in batches, remember that the second batch will usually be quicker as the air fryer has heated up.\n\nStep 3 :\nRemove the bacon using tongs and put on kitchen paper to drain before serving.",
    time: "10m",
  ),
  Meals(
    name: "Chicken Pasta Bake",
    difficulty: "Easy",
    url: "assets/images/meals/pasta/ChickenPastaBake.jpg",
    ingredients: {
      oliveOil: "4 Tablespoon",
      onion: "1",
      garlic: "2 Cloves",
      pepper: "1 Teaspoon chilli one",
      tomato: "800g Chopped one",
      sugar: "1 Teaspoon",
      cheese: "6 Tablespoon Mascarpone",
      chicken: "4 Skinless breasts",
      pasta: "300g Penne",
      cheeseD1: "70g Cheddar",
      cheeseD2: "50g Mozzarella",
      parsley: "Small bunch of it",
    },
    category: "Pasta",
    description:
        "Step 1 :\nHeat 2 tbsp of the oil in a pan over a medium heat and fry the onion gently for 10-12 mins. Add the garlic and chilli flakes and cook for 1 min. Tip in the tomatoes and sugar and season to taste. Simmer uncovered for 20 mins or until thickened, then stir through the mascarpone.\n\nStep 2 :\nHeat 1 tbsp of oil in a non-stick frying pan. Season the chicken and fry for 5-7 mins or until the chicken is cooked through.\n\nStep 3 :\nHeat the oven to 220C/200C fan/gas 7. Cook the penne following pack instructions. Drain and toss with the remaining oil. Tip the pasta into a medium sized ovenproof dish. Stir in the chicken and pour over the sauce. Top with the cheddar, mozzarella and parsley. Bake for 20 mins or until golden brown and bubbling.",
    time: "1h 15m",
  ),
  Meals(
    name: "Caponata Pasta",
    difficulty: "Easy",
    url: "assets/images/meals/pasta/CaponataPasta.jpg",
    ingredients: {
      oliveOil: "4 Tablespoon",
      onion: "1",
      garlic: "4 Cloves",
      pasta: "250g chargrilled Mediterranean veg",
      tomato: "400g Chopped one",
      raisin: "2 Tablespoon",
      pastaD1: "350g rigatoni or penne",
      basil: "Bunch of it",
      cheese: "Parmesan for Serve",
    },
    category: "Pasta",
    description:
        "Step 1 :\nHeat the oil in a large pan and cook the onion for 8-10 mins until starting to caramelise (or for longer if you have time – the sweeter the better). Add the garlic for the final 2 mins of cooking time.\n\nStep 2 :\nTip in the mixed veg, tomatoes, capers and raisins. Season well and simmer, uncovered, for 10 mins, or until you have a rich sauce.\n\nStep 3 :\nMeanwhile, boil the kettle. Pour the kettleful of water into a large pan with a little salt and bring back to the boil. Add the pasta and cook until tender with a little bite, then drain, reserving some of the pasta water. Tip the pasta into the sauce, adding a splash of pasta water if it needs loosening. Scatter with the basil leaves and parmesan, if you like, and serve straight from the pan",
    time: "20m",
  ),
  Meals(
    name: "Chicken & Bacon Pasta",
    difficulty: "Easy",
    url: "assets/images/meals/pasta/ChickenAndBaconPasta.jpg",
    ingredients: {
      oliveOil: "2 Tablespoon",
      onion: "1",
      butter: "1 Tablespoon",
      garlic: "1 Cloves",
      cheeseD1: "100g Mascarpone",
      cream: "200ml Double one",
      cheese: "75g Paemesan",
      chicken: "1 Stock Cube & 2 choocked breasts",
      bacon: "8 Rashers cooked streaky",
      pasta: "300g Tagliatelle",
      parsley: "Bunch of it",
    },
    category: "Pasta",
    description:
        "Step 1 :\nHeat the oil and butter in a medium saucepan over a low heat and fry the onion for 10 mins, or until softened and translucent. Add the garlic and cook for 2 mins more. Add the cream, mascarpone, parmesan and stock cube. Give it a stir and add the cooked chicken and bacon to heat through.\n\nStep 2 :\nMeanwhile, cook the pasta following pack instructions. Reserve 100ml of the pasta water. Toss the pasta in the creamy sauce and enough of the reserved water to loosen. Season with black pepper. Top with the parsley and serve with a green salad.",
    time: "40m",
  ),
  Meals(
    name: "Creamy Mushroom Pasta",
    difficulty: "Easy",
    url: "assets/images/meals/pasta/CreamyMushroomPasta.jpg",
    ingredients: {
      oliveOil: "2 Tablespoon",
      butter: "1 Tablespoon",
      onion: "1",
      wine: "100ml Dry White one",
      garlic: "1 Cloves",
      lemon: "1",
      cream: "200ml Double one",
      cheese: "200gg Paemesan",
      pasta: "300g Tagliatelle or linguini",
      parsley: "Bunch of it",
    },
    category: "Pasta",
    description:
        "Step 1 :\nHeat the oil and butter in a medium saucepan. Fry the onion over a low heat for 10 mins or until softened and translucent.\n\nStep 2:\nAdd the mushrooms and cook for 10 mins over a medium heat. Add the garlic and cook for 2 mins. Add the wine and bring to a simmer, reduce the liquid by half.\n\nStep 3 :\nAdd the double cream and bring to a simmer, then add the lemon zest and parmesan. Season with salt and plenty of black pepper.\n\nStep 4 :\nMeanwhile, cook the pasta following pack instructions. Reserve 100ml of the pasta water. Toss the pasta in the pan with the creamy sauce and enough of the reserved water to loosen. Stir through the parsley, divide into bowls and top with extra cheese, if you like.",
    time: "40m",
  ),
  Meals(
    name: "Easy Tomato Pasta",
    difficulty: "Easy",
    url: "assets/images/meals/pasta/EasyTomatoPasta.jpg",
    ingredients: {
      oliveOil: "1 Tablespoon",
      onion: "1",
      garlic: "1 Cloves",
      tomato: "400g Chopped one",
      sugar: "Pinch of it",
      pasta: "100g Rigatoni",
      cheese: "50g Gruyère or cheddar",
      bread: "Some slices",
      sausage: "2 Frankfurters"
    },
    category: "Pasta",
    description:
        "Step 1 :\nHeat the oil in a medium pan and fry the onion for 5 mins until softened and lightly golden. Stir in the garlic and cook for a further min. Mix in the tomatoes and sugar, bring to the boil and simmer for 20 mins. Add a few dashes of Worcestershire sauce and season to taste. This basic sauce can now be chilled or frozen.\n\nStep 2 :\nMeanwhile, cook the pasta according to pack instructions. Heat the grill to high. Mix together the cheese and breadcrumbs.\n\nStep 3 :\nDrain the pasta and stir into the sauce. Tip in the frankfurters (if using) and spoon into a heatproof dish. Scatter over the cheesy crumbs and grill for 3-5 mins or until bubbling hot and golden. Serve with a simple salad.",
    time: "40m",
  ),
  Meals(
    name: "Creamy Courgette & Bacon Pasta",
    difficulty: "Easy",
    url: "assets/images/meals/pasta/CreamyCourgetteAndBaconPasta.jpg",
    ingredients: {
      oliveOil: "1 Teaspoon",
      bacon: "150g smoked one",
      courgette: "4",
      garlic: "1 Cloves",
      cheese: "A little bit of Parmesan",
      cream: "200g Low-fat crème Fraîche",
      pasta: "300g Tagliatelle",
    },
    category: "Pasta",
    description:
        "Step 1 :\nHeat the olive oil in a large frying pan and sizzle the pancetta or bacon for about 5 mins until starting to crisp. Turn up the heat and add the grated courgette to the pan. Cook for 5 mins or until soft and starting to brown then add the garlic and cook for a minute longer. Season and set aside.\n\nStep 2 :\nCook the tagliatelle according to the pack instructions and scoop out a cupful of cooking water. Drain the tagliatelle and tip into the frying pan with the bacon and courgette. Over a low heat toss everything together with the crème fraiche and half the Parmesan adding a splash of pasta water too if you need to loosen the sauce. Season to taste and serve twirled into bowls with the remaining Parmesan scattered over.",
    time: "30m",
  ),
  Meals(
    name: "Cheesy Ham & Broccoli Pasta",
    difficulty: "Easy",
    url: "assets/images/meals/pasta/CheesyHamBroccoliPasta.jpg",
    ingredients: {
      oil: "1 Teaspoon",
      broccoli: "1 head",
      pasta: "300g Conchiglie",
      onion: "1",
      garlic: "2 Cloves",
      bacon: "250g Ham",
      cream: "300ml pot double cream",
      mustard: "1 Tablespoon",
      cheese: "150g Mature Cheddar"
    },
    category: "Pasta",
    description:
        "Step 1 :\nBring a large pan of water to the boil and cook the pasta following pack instructions, adding the broccoli florets to the pan for the final 4 mins. Drain and set aside.\n\nStep 2 :\nMeanwhile, make the sauce. Heat the oil in a large pan and cook the onion for 5 mins to soften, then stir in the garlic and cook for 1 min more. Stir in the ham, cream and mustard, then bring to the boil. Add the pasta and broccoli, then stir in the cheese, coating everything in the sauce.",
    time: "30m",
  ),
  Meals(
    name: "Pasta Alla Vodka",
    difficulty: "Easy",
    url: "assets/images/meals/pasta/PastaAllaVodka.jpg",
    ingredients: {
      oliveOil: "2 Teaspoon",
      onion: "0.5",
      garlic: "3 Cloves",
      pepper: "0.25 Teaspoon chilli",
      tomato: "100g Purée",
      alcohol: "4 Tablespoon Vodka",
      cream: "100ml Double cream",
      pasta: "200g Penne or Rigatoni",
      cheese: "30g Parmesan",
      basil: "Bunch of it",
    },
    category: "Pasta",
    description:
        "Step 1 :\nHeat the oil in a large frying pan or casserole dish. Add the shallot and a large pinch of salt and gently fry over a low heat for 10 mins or until softened and translucent. Add the garlic and chilli flakes and cook for 30 seconds. Stir through the tomato purée, cook for 2 mins, then stir through the vodka and cook for 3 mins. Quickly stir through the cream to combine, then remove from the heat.\n\nStep 2 :\nCook the pasta in salted water following pack instructions. Drain and reserve 150ml cooking water. Add roughly 50ml of the water to the tomato sauce, then tip in the pasta and cheese, tossing everything together over a low heat until well coated and glossy (loosen with a splash more of the cooking water if it’s a little dry). Season to taste, then serve with a sprinkling of the extra parmesan, a good grinding of black pepper and the basil leaves scattered over the top.",
    time: "30m",
  ),
  Meals(
    name: "Sausage Pasta",
    difficulty: "Easy",
    url: "assets/images/meals/pasta/SausagePasta.jpg",
    ingredients: {
      oliveOil: "1 Teaspoon",
      sausage: "8 Pork sausage",
      onion: "1",
      garlic: "2 Cloves",
      pepper: "1 Teaspoon chilli",
      tomato: "400g",
      pasta: "300g Farfalle or Fusilli",
    },
    category: "Pasta",
    description:
        "Step 1 :\nPut a large pan of water on to boil.\n\nStep 2 :\nHeat 1 tbsp olive oil in a large frying pan and fry chunky pieces of 8 pork sausages on a fairly high heat until they are golden brown all over.\n\nStep 3 :\nNow turn the heat down and add 1 large chopped onion and 2 crushed garlic cloves, cooking them until they have softened.\n\nStep 4 :\nStir in 1 tsp chilli powder and 400g chopped tomatoes with the sausages, bring the sauce to the boil then turn the heat down and let it bubble for about 10 minutes while you cook the pasta.\n\nStep 5 :\nDrop 300g pasta into the pan of boiling water and cook according to the pack instructions.\n\nStep 6 :\nDrain the pasta, then tip it into the frying pan with the sausage sauce, mixing well to coat. Dish up immediately with crusty bread.",
    time: "30m",
  ),
  Meals(
    name: "Bacon & Mushroom Pasta",
    difficulty: "Easy",
    url: "assets/images/meals/pasta/BaconAndMushroomPasta.jpg",
    ingredients: {
      pasta: "400g Penne",
      mushroom: "250g",
      bacon: "8 Rashers Streaky",
      sauce: "4 Tablespoon Pesto",
      cream: "200ml 50% Fat",
      basil: "Bunch of it"
    },
    category: "Pasta",
    description:
        "Step 1 :\nCook the pasta in boiling water in a large non-stick saucepan according to pack instructions. Meanwhile, slice the mushrooms and snip the bacon into bite-size pieces with scissors or a sharp knife.\n\nStep 2 :\nReserve a few drops of the cooking water in a cup or bowl, then drain the pasta and set aside. Fry the bacon and mushrooms in the same pan until golden, about 5 mins. Keep the heat high so the mushrooms fry in the bacon fat, rather than sweat.\n\nStep 3 :\nTip the pasta and reserved water back into the pan and stir over the heat for 1 min. Take the pan off the heat, spoon in the pesto and crème fraîche and most of the basil and stir to combine. Sprinkle with the remaining basil to serve.",
    time: "25m",
  ),
  Meals(
    name: "Chunky Sausage & Tomato Pasta",
    difficulty: "Easy",
    url: "assets/images/meals/pasta/ChunkySausageAndTomatoPasta.jpg",
    ingredients: {
      oliveOil: "1 Teaspoon",
      sausage: "4 Thick Pork one",
      garlic: "2 Cloves",
      wine: "200ml White one",
      tomato: "400g chopped + 1 Tablespoon puree",
      pasta: "500g Rigatoni or Penne",
      cheese: "Parmesan, to serve",
      basil: "Bunch of it",
    },
    category: "Pasta",
    description:
        "Step 1 :\nHeat the olive oil in a heavy-based pan (preferably not non-stick) and add the sausages. Fry for about 8 mins until golden and cooked through. Tip in the garlic and fry for 1 min. Pour in the white wine and boil until it has reduced by half.\n\nStep 2 :\nStir in the tomato purée and tomatoes, and season to taste. Simmer for 15 mins until the sauce is rich and thick.\n\nStep 3 :\nWhile the sauce cooks, boil the pasta according to pack instructions and drain. Stir in the basil if using, and cooked pasta into the sauce, then serve in bowls with grated or shaved Parmesan.",
    time: "25m",
  ),
  Meals(
    name: "Homemade Pasta",
    difficulty: "Easy",
    url: "assets/images/meals/pasta/HomemadePasta.jpg",
    ingredients: {
      flour: "300g Pasta flour + semolina flour",
      egg: "2 and 4 Yolks",
    },
    category: "Pasta",
    description:
        "Step 1 :\nPut the flour in a food processor with ¾ of your egg mixture and a pinch of salt. Blitz to large crumbs – they should come together to form a dough when squeezed (if it feels a little dry gradually add a bit more egg). Tip the dough onto a lightly floured surface, knead for 1 min or until nice and smooth – don’t worry if it’s quite firm as it will soften when it rests. Cover with cling film and leave to rest for 30 mins.\n\nStep 2 :\nCut away ¼ of the dough (keep the rest covered with cling film) and feed it through the widest setting on your pasta machine. (If you don’t have a machine, use a heavy rolling pin to roll the dough as thinly as possible.) Then fold into three, give the dough a quarter turn and feed through the pasta machine again. Repeat this process once more then continue to pass the dough through the machine, progressively narrowing the rollers, one notch at a time, until you have a smooth sheet of pasta. On the narrowest setting, feed the sheet through twice.\n\nStep 3 :\nCut as required to use for filled pastas like tortellini, or cut into lengths to make spaghetti, linguine, tagliatelle, or pappardelle. Then, dust in semolina flour and set aside, or hang until dry (an hour will be enough time.) Store in a sealed container in the fridge and use within a couple of days, or freeze for 1 month.",
    time: "35m",
  ),
  Meals(
    name: "Greek Salad",
    difficulty: "Easy",
    url: "assets/images/meals/salad/GreekSalad.jpg",
    ingredients: {
      tomato: "4 large",
      cucumber: "1",
      onion: "0.5 Red one",
      olive: "16",
      oregano: "1 Teaspoon",
      cheese: "85g Feta",
      oliveOil: "4 Tablespoon"
    },
    category: "Salad",
    description:
        "Step 1 :\nPlace 4 large vine tomatoes, cut into wedges, 1 peeled, deseeded and chopped cucumber, ½ a thinly sliced red onion, 16 Kalamata olives, 1 tsp dried oregano, 85g feta cheese chunks and 4 tbsp Greek extra virgin olive oil in a large bowl.\n\nStep 2 :\nLightly season, then serve with crusty bread to mop up all of the juices.",
    time: "15m",
  ),
  Meals(
    name: "Green Goddess Salad",
    difficulty: "Easy",
    url: "assets/images/meals/salad/GreenGoddessSalad.jpg",
    ingredients: {
      fennel: "2 heads",
      lettuce: "4 baby gem",
      cucumber: "1",
      onion: "1 bunch spring one",
      info: "For The Dressing",
      mustard: "1 Tablespoon",
      vinegar: "2 Tablespoon red wine",
      oliveOil: "6 Tablespoon",
    },
    category: "Salad",
    description:
        "Step 1 :\nTip the dressing ingredients into a jar with a splash of water and shake well.\n\nStep 2 :\nTip the salad into a bowl and keep in the fridge for up to a day. Before serving, dress the salad.",
    time: "20m",
  ),
  Meals(
    name: "Potato Salad",
    difficulty: "Easy",
    url: "assets/images/meals/salad/PotatoSalad.jpg",
    ingredients: {
      potato: "800g",
      onion: "3",
      mayonnaise: "3 Tablespoon",
      oliveOil: "3 Tablespoon",
      vinegar: "1 Tablespoon white wine",
      parsley: "1 small",
    },
    category: "Salad",
    description:
        "Step 1 :\nBoil the potatoes in salted water for 20 mins until just cooked, drain, then cool.\n\nStep 2 :\nCut the potatoes into chunks, then throw into a bowl with the shallots, capers and cornichons, if using. Add enough mayonnaise to bind, then mix together the olive oil and vinegar and add just enough to give a little sharpness to the salad. Stir in the finely chopped parsley and serve.",
    time: "40m",
  ),
  Meals(
    name: "Salade niçoise",
    difficulty: "Easy",
    url: "assets/images/meals/salad/SaladeNicoise.jpg",
    ingredients: {
      potato: "8",
      bean: "50g Green Beans",
      egg: "3",
      lettuce: "2 Little",
      olive: "50g black",
      tomato: "2 meduim",
      tuna: "145g",
      info: "For The Dressing",
      garlic: "0.5 clove",
      fish: "1 anchovy",
      mustard: "1 Tablespoon",
      vinegar: "2 Tablespoon red wine",
      oliveOil: "4 Tablespoon",
    },
    category: "Salad",
    description:
        "Step 1 :\nTo make the dressing, mash the garlic and anchovy, if using, with a small pinch of salt on a board using the blade of a large knife, or in a pestle and mortar. Combine the paste with the mustard and vinegar, then slowly stir in the tuna oil. Set aside.\n\nStep 2 :\nTip the new potatoes into a large pan of cold salted water, ensuring they’re well covered. Bring to the boil, then reduce the heat to a simmer. Add the beans and cook for 5 mins, then remove with a slotted spoon and immediately plunge into a bowl of iced water to cool. Cook the potatoes for another 5 mins until tender, then drain and leave to cool. When cool enough to handle, halve or quarter them, and toss in a large bowl with 1 tbsp of the dressing. Leave to cool completely.\n\nStep 3 :\nMeanwhile, cook the eggs in a second pan of simmering water for 7½ mins, then transfer to a bowl of iced water to cool. Drain the beans and eggs, then peel and halve the eggs.\n\nStep 4 :\nTip the lettuce quarters, cooked beans and olives into the bowl with the potatoes. Add most of the remaining dressing and gently toss. Divide the salad between two bowls, and top with the tomatoes and eggs. Flake over the tuna, then drizzle with the rest of the dressing and season.",
    time: "35m",
  ),
  Meals(
    name: "Kabab Koobideh",
    difficulty: "Easy",
    url: "assets/images/meals/persian/Koobideh.jpg",
    ingredients: {
      beef: "500g",
      onion: "1",
      garlic: "4",
      powder: "1 Tablespoon Turmeric",
      powderD1: "1 teaspoon Paprika",
      redPepper: "1 teaspoon mild",
      powderD2: "2 pinches Cumin",
    },
    category: "Persian",
    description:
        "Step 1 : PREPARATION OF KOUBIDEH SKEWERS\nFinely chop the onion and garlic. Mix the onion, garlic and minced meat, then add the spices (turmeric, cumin, paprika and sweet pepper), parsley and cilantro. Mix everything and keep in the fridge for a few hours.\n\nStep 2 :\nShape long sausages of minced meat on skewers (preferably metal). Flatten them with your hands and brush them with olive oil with a brush.\n\nStep 3 : COOKING BEEF KOOBIDEH SKEWERS\nIn The Oven : \nPreheat the oven to 200 ° C. Place your Koobideh skewers on a lightly oiled baking sheet and bake at 200 ° C for 5 to 10 minutes.\nAt the barbecue:\nPlace your Koobideh skewers on the barbecue, and turn over halfway through cooking (5 minutes on each side).",
    time: "30m",
  ),
  Meals(
    name: "Joojeh Kabab",
    difficulty: "Easy",
    url: "assets/images/meals/persian/JoojehKabab.jpg",
    ingredients: {
      chicken: "800g Breast",
      onion: "2",
      lemon: "Juice of",
      zaferan: "1 half teaspoon",
      oliveOil: "4 tablespoon",
    },
    category: "Persian",
    description:
        "Step 1 : PREPARATION OF THE JUJEH KABAB MARINADE\nIn a salad bowl, mix the chopped onion, the olive oil, the juice of one or two lemons, the saffron diluted in hot water, the salt and the pepper. Mix everything well.\n\nStep 2 : MARINATE YOUR CHICKEN\nCut your chicken breasts into small pieces of about 3 to 4cm then add your chicken to the salad bowl containing the lemon and saffron marinade. Make sure all the chicken pieces are completely coated with the marinade. Cover your marinated chicken with plastic wrap and store in the fridge for at least 6 hours to soak up the delicious Joojeh Kabab marinade.\n\nStep 3 : PREPARING AND COOKING JOOJEH SKEWERS\nOnce the chicken is well marinated, take it out of the fridge and thread the marinated chicken pieces onto flat metal skewers. Cook your Djoudjeh Kabab skewers on the barbecue about 10 cm above the flames and grill the chicken for 5 to 7 minutes on each side. Make sure the Joojeh kabab is well cooked by cutting a piece of chicken with a knife. If it's white and juicy, your Joojeh Kabab skewers are ready to eat!If you don't have a barbecue, you can also cook your skewers in a pan over high heat.",
    time: "25m",
  ),
  Meals(
    name: "Tahdig & Rice",
    difficulty: "Medium",
    url: "assets/images/meals/persian/Tahdig.jpg",
    ingredients: {
      rice: "1 Bowl",
      zaferan: "According to your taste",
      butter: "50g"
    },
    category: "Persian",
    description:
        "Step 1 : RICE PREPARATION\nWash the rice several times in clean water until the water becomes translucent.Fill a bowl with water and a pinch of salt then soak your rice in it for 30 minutes to remove all the starch from the rice.\n\nStep 2 : \nBoil water with coarse salt and cook the rice for 7 to 8 minutes so that it is not fully cooked and remains crunchy. To stop the cooking, rinse the rice in cold water.\n\nStep 3 : PREPARATION OF SAFFRON WATER\nIn a small bowl, dissolve the saffron in 3 tablespoons of hot water until the water is colored.\n\nStep 4 : COOKING RICE IN THE BOTTOM (TAH) OF THE PAN (DIG)\nIn a pressure cooker or sticky pan, melt the butter and add the saffron water.\n\nStep 5 :\nSpread a layer of rice in the bottom of the pan, packing it in well, then repeat the operation with the rest of the rice.\n\nStep 6 :\nCover the lid with a clean tea towel and place the lid on your pan.Cook the rice over very low heat for 40 minutes, the tea towel will absorb the moisture from the rice.\nWarning: NEVER lift the lid before the end of cooking!\n\nStep 7 :\nOnce the rice is cooked (you will hear the rice crackling) invert the pan on a plate as if you were unmolding a cake, being careful not to break your homemade Tahdig.",
    time: "55m",
  ),
  Meals(
    name: "Khoresh Gheymeh",
    difficulty: "Medium",
    url: "assets/images/meals/persian/KhoreshGheymeh.jpg",
    ingredients: {
      meat: "0.5kg Lamb",
      onion: "1",
      bean: "150g Yello Peas",
      powder: "0.5 Tablespoon Turmeric",
      tomato: "1 Tablespoon Paste",
      lemon: "2.5 Amani",
      potato: "2",
      zaferan: '0.5 Teaspoon',
      rice: "200g",
    },
    category: "Persian",
    description:
        "Step 1 :\nCut the meat into cubes and mince the onions. Melt a knob of butter in a large casserole dish over medium heat and add the meat, chopped onions, turmeric and black pepper. Grill for 10 minutes.\n\nStep 2 :\nCover everything with water (about 3 glasses), cover the casserole dish and cook over low / medium heat for 30 minutes until the meat is tender.\n\nStep 3 : CLEANING AND PRE-COOKING YELLOW PEAS\n Meanwhile, rinse the yellow peas in cold water and pre-cook them in boiling water for 5 to 6 minutes with a bit of salt until they are quite tender but still firm.Rinse them in cold water after pre-cooking and set them aside.\n\nStep 4 :\nAdd to the meat: the tomato paste, the yellow peas, 2 tablespoons of butter, 5 limoo amani (or lemon juice if you do not have any), a teaspoon of saffron and let it simmer for several hours. (2h minimum)\n\nStep 5 : PREPARATION OF FRENCH FRIES\nWhile the Khoresh Gheymeh is simmering gently, peel your potatoes and cut them into small fries.Place them in a colander and rinse them with cold water to get rid of the starch.Wipe them with paper.If you are using saffron, sprinkle them.\n\nStep 6 :\nHeat some frying oil in a pan or deep fryer and fry your fries for 10 to 15 minutes until golden color.",
    time: "4h 15m",
  ),
  Meals(
    name: "Ghormeh Sabzi",
    difficulty: "Medium",
    url: "assets/images/meals/persian/GhormehSabzi.jpg",
    ingredients: {
      meat: "0.5kg Lamb",
      bean: "150g Red Beans",
      onion: "1",
      parsley: "2 bunch",
      herb: "0.5 bunch Coriander",
      herbD1: "100g Leeks",
      herbD2: "2 Green Onions",
      herbD3: "0.5 bunch Fenugreek",
      lemon: "3 Amani",
      powder: "0.5 Tablespoon Turmeric",
    },
    category: "Persian",
    description:
        "Step 1 : HERBS\nWash the herbs, dry them and finely chop them with the leeks and green onions.\n\nStep 2 :\nHeat some oil in a frying pan and cook the fresh herbs for 10 minutes while stirring.\n\nStep 3 : PREPARATION OF GHORMEH SABZI\nIn a large pot, brown the chopped onions in a little oil until golden brown.\n\nStep 4 :\nAdd the meat (lamb or beef), turmeric, salt and pepper to the onions and cook for about ten minutes.\n\nStep 5 :\nAdd the red beans, the chopped and fried herbs and the limoo amani (dried lemons) that you have to pierce with a fork or a knife.\n\nStep 6 :\nAdd water until everything is covered. Cover the pot and simmer over medium heat for 2 hours.Note: the longer your Ghormeh Sabzi simmers, the more flavorful it will be. If you have time",
    time: "2h 15m",
  ),
  Meals(
    name: "Sholeh Zard",
    difficulty: "Medium",
    url: "assets/images/meals/persian/SholehZard.jpg",
    ingredients: {
      rice: "250g",
      sugar: "500g",
      butter: "125g",
      zaferan: "1 Teaspoon",
      alcohol: "2 Teaspoon Rose water",
      nuts: "2 Teaspoon Flaked Almonds",
      water: "2L",
    },
    category: "Persian",
    description:
        "Step 1 :\nWash the rice thoroughly to remove all the starch.\n\nStep 2 :\nCook the rice in 2L of water for about 35 minutes.\n\nStep 3 :\nAdd the sugar and cook, stirring constantly, for 15 minutes. Add the saffron powder, diluted in a little hot water.\n\nStep 4 :\nAdd the butter, flaked almonds and rose water and cook for 40 minutes over low heat, stirring occasionally until a pudding consistency is achieved.\n\nStep 5 :\nPour the mixture into rammequins or a deep dish and garnish with pistachios or almonds and cinnamon.\n\nStep 6 :\nLet it rest in the fridge and serve chilled.",
    time: "2h",
  ),
  Meals(
    name: "Koukou Sibzamini",
    difficulty: "Easy",
    url: "assets/images/meals/persian/KoukouSibzamini.jpg",
    ingredients: {
      potato: "2",
      onion: "0.5",
      garlic: "1 Clove",
      backingPowder: "0.5 Teaspoon",
      powder: "0.5 Teaspoon Turmeric",
      zaferan: "0.25 Teaspoon",
      egg: "1",
    },
    category: "Persian",
    description:
        "Step 1 : PREPARATION OF THE KOUKOU SIBZAMINI\nCook the potatoes in water and grate or mash them in a salad bowl.\nNote: it is better to wait for the potatoes to cool before grating or mashing them. Your koukou will hold up better when cooked.\n\nStep 2 :\nFry the onions in a separate pan and finely chop the garlic.\n\nStep 3 :\nAdd the egg, cooked onions, minced garlic, yeast, turmeric, saffron (optional), salt and pepper to the grated or mashed potatoes. You can also add herbs like parsley or basil.Mix everything well.\n\nStep 4 :\nHeat some sunflower oil in a pan. Form small round croquettes with your hands, lower the heat and add the koukou to the pan.For a good cooking, make sure that the Koukou is 3cm thick at most.\n\nStep 5 :\nFry the Koukou Sibzamini on one side then turn it over using a plate or a flat lid. Leave to cook over low heat for a few minutes.\n\nStep 6 :\nTake your koukou out of the pan and wring it out using a paper towel to remove the fat.",
    time: "30m",
  ),
  Meals(
    name: "Koukou Sabzi",
    difficulty: "Medium",
    url: "assets/images/meals/persian/KoukouSabzi.jpg",
    ingredients: {
      egg: "6",
      parsley: "100g",
      herb: "100g Coriander",
      herbD1: "80g Dill",
      onion: "5 Shallots",
      nuts: "	4 Chopped nuts",
      oil: "2 Teaspoon",
      backingPowder: "1 Teaspoon",
    },
    category: "Persian",
    description:
        "Step 1 :\nWash and chop the herbs, shallots and salad leaves in a blender or with a kitchen knife and place them in a salad bowl.\n\nStep 2 :\nIn a bowl, break the eggs, add the baking powder, chopped nuts, sunflower oil, salt and pepper then beat everything together with a whisk.\n\nStep 3 :\nAdd the mixture to the chopped herbs and mix well.\n\nStep 4 : COOKING\n2 options: in the pan or in the oven \nIn the pan: Heat a little oil in the pan, add the mixture and spread it well. Cook for 10 minutes on low heat then turn the Koukou Sabzi using a plate then finish cooking for another 10 minutes\nIn the oven: Oil a round mold, place the mixture in it and put the Koukou Sabzi in an oven preheated to 180 ° C. Cook for about 30 minutes.",
    time: "45m",
  ),
  Meals(
    name: "Ashe Jo",
    difficulty: "Easy",
    url: "assets/images/meals/persian/AsheJow.jpg",
    ingredients: {
      herb: "1 Shallots",
      butter: "0.5 Tablespoon",
      powder: "0.5 Teaspoon Turmeric",
      powderD1: "0.5 teaspoon Cumin",
      info: "Bechamel Sauce",
      butterD1: "1 Tablespoon",
      flour: "1 Tablespoon",
      milk: "1 Cup",
      parsley: "1 Tablespoon Chopped",
    },
    category: "Persian",
    description:
        "Step 1 :\nHeat the butter in a pot or large saucepan. Add the diced shallots and sauté until translucent. Add cumin and turmeric.Add the previously cooked barley and 3 cups of chicken stock and bring the mixture to a boil. Cover the pan and simmer over medium-low heat for 30 minutes or until thickened.\n\nStep 2 :\nAdd the grated carrot, an extra cup of chicken broth and salt & pepper. Bring to a boil and simmer another 20 minutes, until thickened; keep your Ashe-e-Jo on the stove over medium-low heat.\n\nStep 3 : PREPARATION OF THE BECHAMEL SAUCE\nHeat 2 tablespoons of butter in a small saucepan and add 2 tablespoons of flour. Stir for 2 minutes until the flour has a golden color.Add a cup of milk and beat constantly with a whisk over medium heat until the bechamel sauce thickens.Add another cup of milk, heat until mixture is hot but not boiling.\n\nStep 4 : ADDING BECHAMEL SAUCE TO YOUR ASH-E-JO\nBring the soup to a boil over medium-high heat and add the hot bechamel sauce while stirring.\n\nStep 5 :\nReduce the heat to medium and cook the Ashe Jow uncovered for 10 minutes or until the soup thickens. Stir frequently.\n\nStep 6 :\nAdd the lemon juice and remove the soup from the heat. Finely chop some parsley and add it.",
    time: "1h 30m",
  ),
  Meals(
    name: "Ashe Reshteh",
    difficulty: "Medium",
    url: "assets/images/meals/persian/AsheReshteh.jpg",
    ingredients: {
      bean: "50g Red beans",
      beanD1: "50g green lentils",
      beanD2: "50g Chickpeas",
      herb: "150g Spinach leaves",
      pasta: "125g Reshteh",
      onion: "1",
      parsley: "0.5 bouquet",
      herbD1: "0.5 bunch Chives",
      herbD2: "1 Tablespoon dried mint",
      garlic: "1 Clove",
      yogurt: "25-100g Kashk",
      powder: "0.5 Teaspoon Turmeric",
    },
    category: "Persian",
    description:
        "Step 1 :\nWash the bunch of parsley and the bunch of coriander, then drain them. Finely chop the bouquets of herbs.\n\nStep 2 :\nRinse the cans of red beans, lentils and chickpeas under running water. If you have non-pre-cooked legumes, cook them, but not too much! Your legumes need to stay a bit firm.\n\nStep 3 :\nOnce the legumes have been washed (or pre-cooked), pour them with the spinach into a large Dutch oven and cover with water.Cover and simmer over medium heat.Add the chopped herbs to the pot with a tablespoon of dried mint.\n\nStep 4 :\nPour the pasta (Reshteh or spaghetti, linguine) into the soup and cook for about 30 minutes.If you are using spaghetti or linguine, add them 10 minutes before the soup is finished cooking.Reshteh have the ability to cook without decomposing.\n\nStep 5 :\nMeanwhile prepare chop the onions and fry them in oil until they are golden brown.Chop the garlic cloves and fry them for 2-3 minutes in a pan when the onions are golden brown, adding the turmeric.\n\nStep 6 :\nPour a little kashk (at your convenience) in the soup and dilute it.",
    time: "35m",
  ),
  Meals(
    name: "Adas Polo",
    difficulty: "Medium",
    url: "assets/images/meals/persian/AdasPolo.jpg",
    ingredients: {
      rice: "1.2 cups",
      bean: "0.3 cup Green Lentils",
      zaferan: "Your taste",
      onion: "1",
      cinnamon: "0.6 pinch",
      powder: "0.6 teaspoon Turmeric",
      oliveOil: "For fring",
      potato: "0.5 for Tahdig",
    },
    category: "Persian",
    description:
        "Step 1 : PREPARING THE LENTILS\nRinse the lentils several times in cold water then pour them into a saucepan. Add a cup of water to the and bring to a boil over medium-high heat. Reduce the heat to medium-low then add 1 teaspoon of salt, cover and cook for about 20 minutes or until the lentils are tender and there is little liquid left in the pan. Reserve the cooked lentils for later.\n\nStep 2 : RICE PREPARATION\nRinse the rice in cold water, soak it in 3-4 cups of water with 2 tablespoons of salt. Then cook your rinsed rice in boiling water for about ten minutes. The rice should be firm in the center and soft on the outside. Once your rice is cooked, drain it and rinse it with cold water.\n\nStep 3 : PREPARATION OF TOPPINGS\nSauté the chopped onions in 2 tbsp of oil over medium heat until the onions begin to soften, add the turmeric, raisins, dates, a pinch of cinnamon and stir. Lightly sauté for a few minutes then set aside.\n\nStep 4 : PREPARATION OF TAHDIG\n Add a few tablespoons of vegetable oil to a large saucepan. With a spatula, place a layer of cooked rice (or thin slices of potato) in the bottom of the pan, then place a layer of cooked lentils, then another layer of rice. Repeat the process until you run out of rice and lentils. Spread the saffron diluted in water over your layers of Adas Polo.\n\nStep 5 : COOKING YOUR ADAS POLO\nCover the pot and cook for 10 minutes over medium-high heat until the rice is smoking. Lower the heat to medium-low and steam the rice for another 45-50 minutes.Invert the pan onto a large plate and admire your Tahdig Adas Polo!",
    time: "1h 20m",
  ),
  Meals(
    name: "Baghali Polo",
    difficulty: "Easy",
    url: "assets/images/meals/persian/BaghaliPolo.jpg",
    ingredients: {
      rice: "1 Cup",
      water: "4 Cups",
      salt: "1 Tablespoon",
      herb: "0.5 Cup Dill",
      bean: "1 Cup Beans",
      butter: "2 Tablespoons",
      zaferan: "0.25 Teaspoon",
    },
    category: "Persian",
    description:
        "Step 1 : COOKING RICE\nIn a large covered saucepan, bring 8 cups of water and a little salt to a boil. Add the previously rinsed rice and boil over high heat uncovered for about 5 to 7 minutes, until the rice has softened slightly.\n\nStep 2 : PREPARATION OF SAFFRON WATER\nWhile your rice is cooking, dilute 1/4 teaspoon of ground saffron in 2 tablespoons of hot water. Stir slowly.\n\nStep 3 :\nTurn off the heat, scoop out about a cup of cooked rice and place it in a small bowl. Mix with 1 tablespoon of saffron water and mix gently. Set the bowl of rice aside.Add the dill and fresh broad beans to the pan with the rest of the rice and stir gently for 2-3 minutes. Drain the rice, bean and dill mixture in a colander and set aside.\n\nStep 4 :\nMelt 2 tablespoons of butter or olive oil in the same pan over low heat. Then evenly distribute the rice mixed with the saffron water at the bottom of the pan. This layer of rice will form the precious Tahdig (crispy rice).Pour the rest of the mixture of cooked rice, beans and dill into the pan and stir lightly with a spoon. Add two tablespoons of oil on top of the rice.\n\nStep 5 :\nPour a little water (about 1/4 cup) evenly over the top of the rice. Wrap the lid with a clean towel and place it on the jar. This will allow your Baghali Polo to steam.Steam the rice over medium heat for about 45 minutes.\n\nStep 6 :\nPour the remaining tablespoon of saffron water over the top of the rice. Turn off the heat and let cool for 5 minutes before serving.",
    time: "",
  ),
  Meals(
    name: "Salade Olivieh",
    difficulty: "Easy",
    url: "assets/images/meals/persian/SaladeOlivieh.jpg",
    ingredients: {
      potato: "250g Firm-fleshed",
      chicken: "A Shredded",
      cucumber: "100g Pickles",
      herb: "0.67 Bunches green onions",
      egg: "3",
      mayonnaise: "1.5 Teaspoon",
    },
    category: "Persian",
    description:
        "Step 1 : PREPARING THE POTATOES\n Bring salted water to a boil in a large saucepan and cook the potatoes in it for about 12 minutes. (the cooking time depends on the size of the potatoes). Drain them and immerse them in cold water to stop the cooking. Once cold, peel them and cut them into 2.5cm cubes.\n\nStep 2 : ASSEMBLY OF OLIVIEH SALAD\nOnce your potatoes have been peeled and cut, put them in a large salad bowl, add the shredded chicken, finely chopped pickles, chopped green onions and diced hard-boiled eggs. Mix everything by hand, being careful not to crush the ingredients of the Olivieh salad.\n\nStep 3 : PREPARATION OF THE SAUCE FOR THE OLIVIEH SALAD\nIn a bowl, mix the mayonnaise, lemon juice, olive oil then salt and pepper generously.\n\nStep 4 :\nPour the sauce into your large salad bowl and mix it with the Olivier salad with a large spoon. Taste your salad and add a little salt, pepper or lemon juice to your liking.",
    time: "30min",
  ),
  Meals(
    name: "Kotlet",
    difficulty: "Medium",
    url: "assets/images/meals/persian/Kotlet.jpg",
    ingredients: {
      bread: "44g Breadcrumbs",
      beef: "200g",
      potato: "1 Mashed",
      onion: "0.5",
      powder: "8g Coriander",
      egg: "1",
      garlic: "0.8 Teaspoon dried",
      powder: "0.8 Teaspoon Cumin",
      powderD1: "0.4 Teaspoon Turmeric",
      cinnamon: "0.2 Teaspoon",
      salt: "0.8 Teaspoon",
    },
    category: "Persian",
    description:
        "Step 1 :\nSpread the breadcrumbs on a plate.\n\nStep 2 :\nIn a bowl, combine the remaining ingredients, without the oil, while kneading the preparation by hand. The eggs must be perfectly incorporated and the spices well distributed in the mixture.\n\nStep 3 :\nTake some of your meat, potato and spice mixture and roll it in the palms of your hands, then flatten it. Turn it over in the breadcrumbs making sure that both sides are well covered. Do the rest of your Kotlets the same way.\n\nStep 4 :\nPour a little oil in a non-stick pan over high heat and fry your kotlet 6 to 8 minutes per side until nicely golden.Gently take them out of the pan and put them to drain on a plate lined with absorbent paper.",
    time: "15min",
  ),
  Meals(
    name: "Adassi",
    difficulty: "Easy",
    url: "assets/images/meals/persian/Adassi.jpg",
    ingredients: {
      bean: "250g Green lentils",
      onion: "1",
      powder: "1 Teaspoon Turmeric",
      flour: "20g",
      water: "1L",
      yogurt: "1 Greek",
      herb: "How many you like",
      potato: "1"
    },
    category: "Persian",
    description:
        "Step 1 :\nRinse your green lentils in cold water in a colander.\n\nStep 2 : COOKING GREEN LENTILS\nPour them into a pot with 2 liters of water and a cube of vegetable stock. Bring your green lentils to a boil, covered, for about 20 minutes until the lentils are cooked. Salt them to taste.\n\nStep 3 : COOKING ONIONS\nWhile the lentils are cooking, finely chop 2 onions (I use 3 because I love it!) And brown them in a skillet over low heat for about 20 minutes until they become soft and they are lightly brown.\n\nStep 4 :\nThen add two teaspoons of turmeric powder and 40 grams of flour and mix well with the onions.\n\nStep 5 :\nOnce the lentils are cooked and very tender. Add your onions and bring to the boil for 10 minutes. The flour contained in the onion will thicken the soup and give it a velvety side. Give a few turns of the pepper mill.",
    time: "45m",
  ),
  Meals(
    name: "Mirza Ghasemi",
    difficulty: "Medium",
    url: "assets/images/meals/persian/MirzaGhasemi.jpg",
    ingredients: {
      eggplant: "3",
      garlic: "1 Cloves",
      powder: "0.5 teaspoon Turmeric",
      tomato: "3 + 2 Teaspoons Puree",
      sugar: "0.5 Teaspoon",
      salt: "1.5 Teaspoons",
      egg: "1.5",
      nuts: "0.5 handful Crushed nuts",
    },
    category: "Persian",
    description:
        "Step 1 :\nTraditionally, Iranians roast eggplants over the flame of a gas stove or over the embers of a barbecue, turning them until the skin blisters. You can also place them in a large dish and roast them for 40 to 45 minutes in an oven preheated to 220 degrees. (thermostat 7-8)\n\nStep 2 :\nPour olive oil into a large skillet and heat it over medium heat. Let the garlic return to low heat.\n\nStep 3 :\nWhen the garlic begins to brown, add the turmeric then the tomatoes and cook for 15 to 20 minutes until the tomatoes are tender. Remove the pan from the heat.\n\nStep 4 :\nOnce the eggplants are grilled, split the skin all the way up and remove the flesh with a spoon. Mix the eggplant flesh with the garlic and tomato mixture and finish cooking over low heat for 2 to 3 minutes, lightly mashing everything.\n\nStep 5 :\nFinally, add the tomato paste, sugar and fleur de sel and mix well. Leave 6 to 8 minutes on the heat, stirring regularly to prevent the mixture from sticking.\n\nStep 6 :\nMake several small holes in the preparation to pour in the beaten eggs. After 6 minutes of cooking over low heat, they should be firm and opaque. Mix quickly to finish cooking and let stand for 20 minutes.",
    time: "30min",
  ),
  Meals(
    name: "Abgoosht",
    difficulty: "Easy",
    url: "assets/images/meals/persian/Abgoosht.jpg",
    ingredients: {
      beef: "0.5kg",
      onion: "1.5",
      garlic: "1.5 Cloves",
      bean: "175g Chickpeas",
      beanD1: "175g White beans",
      potato: "250g",
      powder: "1 Teaspoon Turmeric",
      lemon: "1.5 Amani",
      tomato: "0.5Kg + 1 Tablespoon Paste",
    },
    category: "Persian",
    description:
        "Step 1 : PREPARATION OF CHICKPEAS\nRinse and drain the chickpeas and white beans.\nNote: The chickpeas should be soaked in water for at least 5 hours before preparation, unless they are canned chickpeas.\n\nStep 2 : BROWN THE MEAT AND ONIONS\nBrown the sliced ​​onions in a pot over medium / low heat and add the lamb or beef.Add salt and pepper.\n\nStep 3 :\nDrill the limoo amani (dried lemons) and add them to the meat and onions.\n\nStep 4 : ADD VEGETABLES\nAdd the white beans, chickpeas, garlic, turmeric, cinnamon, and cover everything with boiling water. Mix well.\n\nStep 5 : COOKING\nCover and cook over medium / low heat for 2h30 while regularly removing the foam that forms on the surface.After 2h30 of cooking, add the tomato paste, the fresh tomatoes, the potatoes, the green pepper and mix well.Cover and cook for 2 hours on low heat.\n\nStep 6 :\n",
    time: "4h 45m",
  ),
  Meals(
    name: "Kashke Bademjan",
    difficulty: "Medium",
    url: "assets/images/meals/persian/KashkeBademjan.jpg",
    ingredients: {
      eggplant: "2",
      onion: "1",
      garlic: "3 Cloves",
      powder: "1 Teaspoon Turmeric",
      nuts: "1 Pinch Walnuts",
      yogurt: "4 Teaspoons Kashke",
      herb: "Some leaves Mint",
    },
    category: "Persian",
    description:
        "Step 1 :\nCut the ends of the eggplants, peel them and cut them into small cubes.\n\nStep 2 :\nBrown the eggplants in a pan with a little olive oil. Meanwhile, peel the onion and garlic cloves and mince them finely.Reserve the eggplants separately.\n\nStep 3 :\nIn the pan where you cooked the eggplant, add the garlic, onion and turmeric and cook over low heat for about ten minutes.\n\nStep 4 :\nThen add the golden eggplants cut into cubes with a small glass of water, cover the pan and cook over low heat for another 10 minutes.Meanwhile, crush the nuts.\n\nStep 5 :\nTake out the eggplant, garlic, onion and turmeric. Mash everything with a fork and add the crushed walnuts. Salt, pepper to your liking.Finally, add the Kashke (Greek yogurt), mint leaves and a tablespoon of olive oil then mix everything.\n\nStep 6 :\nPour the eggplant caviar into a bowl or deep plate, sprinkle with mint leaves and crushed walnuts.",
    time: "35m",
  ),
  Meals(
    name: "Gheymeh Bademjan",
    difficulty: "Easy",
    url: "assets/images/meals/persian/GheymehBademjan.jpg",
    ingredients: {
      meat: "300g Lamb shoulder",
      eggplant: "1 to 3",
      bean: "125g Yellow split peas",
      tomato: "1.5 + 1 Teaspoon Paste",
      garlic: "1.5 Cloves",
      onion: "2",
      lemon: "1.5 Amani",
      powder: "0.5 Teaspoon Cumin",
      nutmeg: "0.5 Teaspoon",
      cinnamon: "1 Teaspoon",
      powderD1: "0.5 Teaspoon Cardamom",
      powderD2: "0.5 Teaspoon Turmeric",
    },
    category: "Persian",
    description:
        "Step 1 : COOKING MEAT\nIn a large sauté pan, put a little oil and brown your pieces of meat cut into cubes over high heat until they are golden brown on all sides, then set them aside. You can very well use other meats than lamb for the Gheymeh Bademjan recipe.\n\nStep 2 : PREPARATION OF VEGETABLES\nWhile the meat is cooking, chop your onions and garlic cloves. Crush the tomatoes and pierce your dried lemons (limou amani) with a fork. Also rinse your yellow split peas in cold water.\n\nStep 3 : COOKING GHYEMEH BADEMJAN\nUse the same sauté pan and lower the heat. Now add the garlic, minced onions and all the spices and brown, stirring constantly. When your onions are golden, add the crushed tomatoes, the tomato concentrate, the previously rinsed split peas, the dried lemons then add your pieces of lamb meat. Pour water just up to it. Be careful, don't put too much. The water should just cover the meat and vegetables in your Khoresht Gheymeh Bademjan.\n\nStep 4 :\nSimmer your Gheymeh Bamdejan over low heat for about 1h20. Mix every 10 minutes or so, checking that the preparation has not dried out too much. Do not hesitate to add a little water if this is the case.\n\nStep 5 : PREPARE YOUR EGGPLANTS\nCut your eggplants into large slices lengthwise. Your eggplant slices should be thin enough to cook well (about 5 mm thick). Brush them with olive oil and bake them in the oven at 210° for a few minutes until they have a nice golden color. The cooking time will depend on the power of your oven as well as the height at which you put them in the oven.Once your aubergines are well grilled, set them aside for the dressing of your Gheymeh Bademjan.Watch your eggplant carefully, it will be the main ingredient of your Khoresht Gheymeh Bademjan!",
    time: "1h 30m",
  ),
  Meals(
    name: "Zereshk Polo Ba Morgh",
    difficulty: "Medium",
    url: "assets/images/meals/persian/ZereshkPoloBaMorgh.jpg",
    ingredients: {
      zaferan: "0.25 Teaspoon",
      rice: "3.5 Cups",
      barberry: "1 Cup",
      onion: "2",
      potato: "2",
      bellPepper: "1",
      water: "4 Cups",
      chicken: "4 Pieces",
      powder: "1 Tablespoon Turmeric",
      powderD1: "0.5 Tablespoon Curry",
      salt: "1 Tablespoon",
      pepper: "1 Tablespoon Blackpepper",
    },
    category: "Persian",
    description:
        "Step 1 : Bloomed Zaferan\nPlace 1 or 2 ice cubes in a tiny glass.Add 1/4 teaspoon of ground saffron.Let it rest till melting the ice cubes.\n\nStep 2 : Chicken in tomato sauce (morgh)\nHeat the frying pan and add a few oils.Sauté chicken pieces in the oil till their color changes into golden-brown.Turn chicken pieces to the other side and fry that side.Peel 2 medium-size onions and chop them into small pieces.Add oil and chopped onions to the frying pan, and fry the onions till making them golden.Add 1 tablespoon of turmeric, 1 tablespoon of salt, red chopped bell pepper, 1 tablespoon of black pepper, and 1/2 tablespoon of curry to the onions and mix them.\n\nStep 3 :\nDilute 2 tablespoons of tomato paste with a glass of water and add it to onions. Tomato sauce is ready!Place sautéed chicken and potatoes (any vegetables you prefer) in the tomato sauce.Pour 1 1/2 tablespoons of bloomed saffron on chicken pieces.Add water until almost covers chicken and vegetables.Let them cook for 80 minutes when the chicken is soft, and the sauce gets strong.\n\nStep 4 : Barberry (zereshk)\nWash 1 cup of barberries, and soak them in cool water for an hour.Sauté barberry in butter and add a tablespoon of sugar to make it sour and sweet.Add a tablespoon of bloomed saffron to barberries\n\nStep 5 : Rice (polo)\nTo wash the 3 1/2 cups of rice, you should pour the rice into a bowl of water and move the rice around the bowl with your hand.Drain the water and add fresh water again. Repeat this move until the water becomes clear.Add salt to the rice in the clear water and let them rest for near 1 hour.Bring a pot and add water into it till half of the pot and let it boil.Drain the water from the rice and pour the rice into the boiling pot. Let the water boil.When the rice comes up, and the rice becomes soft, pour it into a colander and splash cold water on the rice.Put a non-stick pot on the heat, add 4 tbsp vegetable oil and half a cup water, and pour the half-cooked rice into the pot. Allow the rice to steam for 35 minutes.Rice is ready! If rice is dry, add 2 or 3 tablespoons of vegetable oil or butter to it.\n\nStep 6 : Golden rice with barberry (saffron rice with barberry)\nPour 8 tbsp cooked rice in bloomed saffron and stir them to make the rice golden.Add barberries to the golden rice.",
    time: "1h 45m",
  ),
];
// Step 1 :\n\n\nStep 2 :\n\n\nStep 3 :\n\n\nStep 4 :\n\n\nStep 5 :\n\n\nStep 6 :\n
// Meals(
//     name: "",
//     difficulty: "Easy",
//     url: "assets/images/meals/persian/SaladeNicoise.jpg",
//     ingredients: {
//     },
//     category: "Persian",
//     description: "",
//     time: "",
//   ),
