name: meals
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.5
  font_awesome_flutter: ^10.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/meals/breakfast/BP.jpg
    - assets/images/meals/breakfast/AirFryerBacon.jpg
    - assets/images/meals/breakfast/Pancakes.jpg
    - assets/images/meals/breakfast/PoachedEggs.jpg

    - assets/images/meals/salad/GreekSalad.jpg
    - assets/images/meals/salad/PotatoSalad.jpg
    - assets/images/meals/salad/GreenGoddessSalad.jpg
    - assets/images/meals/salad/SaladeNicoise.jpg

    - assets/images/snacks/cookie/CCC.jpg

    - assets/images/snacks/cake/CC.jpg
    - assets/images/snacks/cake/ButterflyCupcakes.jpg
    - assets/images/snacks/cake/LLC.jpg
    - assets/images/snacks/cake/CCF.jpg

    - assets/images/drinks/coffee/cappucino.jpg
    - assets/images/drinks/coffee/flat_white.jpg
    - assets/images/drinks/coffee/latte.jpg
    - assets/images/drinks/coffee/macchiato.jpg
    - assets/images/drinks/coffee/mocha.jpg

    - assets/svg/apple.svg
    - assets/svg/backing_powder.svg
    - assets/svg/backing_soda.svg
    - assets/svg/bacon.svg
    - assets/svg/banana.svg
    - assets/svg/beans.svg

    - assets/svg/beef.svg
    - assets/svg/bell_pepper.svg
    - assets/svg/biscuit.svg
    - assets/svg/bread.svg
    - assets/svg/brown_sugar.svg
    - assets/svg/butter.svg
    - assets/svg/cabbage.svg
    - assets/svg/carrot.svg
    - assets/svg/cheese.svg
    - assets/svg/chicken.svg
    - assets/svg/chocolate.svg
    - assets/svg/cinnamon.svg
    - assets/svg/cocoa.svg
    - assets/svg/coffee.svg
    - assets/svg/cookie.svg
    - assets/svg/cucumber.svg
    - assets/svg/egg.svg
    - assets/svg/fennel.svg
    - assets/svg/fish.svg
    - assets/svg/flour.svg
    - assets/svg/garlic.svg
    - assets/svg/grape.svg
    - assets/svg/ice_cream.svg
    - assets/svg/lemon.svg
    - assets/svg/lettuce.svg
    - assets/svg/mayonnaise.svg
    - assets/svg/meat.svg
    - assets/svg/milk.svg
    - assets/svg/mustard.svg
    - assets/svg/nutmeg.svg
    - assets/svg/nuts.svg
    - assets/svg/oil.svg
    - assets/svg/olive.svg
    - assets/svg/oliveOil.svg
    - assets/svg/onion.svg
    - assets/svg/orange.svg
    - assets/svg/oregano.svg
    - assets/svg/parsley.svg
    - assets/svg/pepper.svg
    - assets/svg/potato.svg
    - assets/svg/raisin.svg
    - assets/svg/red_pepper.svg
    - assets/svg/rise.svg
    - assets/svg/salt.svg
    - assets/svg/sausage.svg
    - assets/svg/sugar.svg
    - assets/svg/tomato.svg
    - assets/svg/tuna.svg
    - assets/svg/vanilla.svg
    - assets/svg/vinegar.svg
    - assets/svg/water.svg
    - assets/svg/yogurt.svg
    - assets/svg/zaferan.svg

    - assets/svg/info.svg

  fonts:
    - family: Lora
      fonts:
        - asset: assets/fonts/Lora-Bold.ttf
        - asset: assets/fonts/Lora-BoldItalic.ttf
        - asset: assets/fonts/Lora-Italic.ttf
        - asset: assets/fonts/Lora-Medium.ttf
        - asset: assets/fonts/Lora-MediumItalic.ttf
        - asset: assets/fonts/Lora-Regular.ttf
        - asset: assets/fonts/Lora-SemiBold.ttf
        - asset: assets/fonts/Lora-SemiBoldItalic.ttf
    - family: Dosis
      fonts:
        - asset: assets/fonts/Dosis-Bold.ttf
        - asset: assets/fonts/Dosis-ExtraBold.ttf
        - asset: assets/fonts/Dosis-ExtraLight.ttf
        - asset: assets/fonts/Dosis-Light.ttf
        - asset: assets/fonts/Dosis-Medium.ttf
        - asset: assets/fonts/Dosis-Regular.ttf
        - asset: assets/fonts/Dosis-SemiBold.ttf
